### ISSUE TITLE
prepare.py fails when there is no code change

### ISSUE THREAD

**Issue by narenst** [floydhub/dockerfiles#5]
ci/prepare.py script fails when there is no code change and the build was started manually.

```
Traceback (most recent call last):
  File "ci/prepare.py", line 69, in <module>
    for dockerfile_path in find_changed_dockerfiles():
  File "ci/prepare.py", line 37, in find_changed_dockerfiles
    git_compare = build_info['compare'].split('/')[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```

cc: @houqp

**Comment by houqp** [comment]
oops, will get that fixed tonight ;P

**Comment by narenst** [comment]
No worries :) Started testing this today, and noticed this!
